[hipfft] Fix Doxygen comments that cause cyclic ref errors
## Motivation

Fix incorrect Doxygen comments that cause cyclic ref errors when
generating docs with sphinx via rocm-docs-build

## Technical Details

Fix incorrect Doxygen \ref usage that caused cyclic reference errors
when generating docs with sphinx via rocm-docs-build. Update comments to
reference the correct public types and remove invalid struct
annotations.
No API or functional changes intended.

Simply changing WARN_AS_ERROR to NO in Doxyfile would not solve the
issue as at the end of the Doxygen process Doxygen will return with a
non-zero status which sphinx will not tolerate.

Log:
```
.
.
Sorting member lists...
Setting anonymous enum type...
Computing dependencies between directories...
Generating citations page...
Counting members...
Counting data structures...
Resolving user defined references...
Finding anchors and sections in the documentation...
Transferring function references...
Combining using relations...
Adding members to index pages...
Correcting members for VHDL...
Computing tooltip texts...
Generating style sheet...
Generating search indices...
<PATH>/hipfft/hipfft/library/include/hipfft/hipfftXt.h:0: error: Potential recursion while resolving \ref command! (warning treated as error, aborting now)
Exiting...

Extension error (rocm_docs.doxygen)!

Versions
========

* Platform:         linux; (Linux-6.14.0-37-generic-x86_64-with-glibc2.42)
* Python version:   3.13.11 (CPython)
* Sphinx version:   8.2.3
* Docutils version: 0.22.4
* Jinja2 version:   3.1.6
* Pygments version: 2.18.0

Last Messages
=============

None.

Loaded Extensions
=================

None.

Traceback
=========

      File "/usr/lib/python3/dist-packages/sphinx/events.py", line 415, in emit
        raise ExtensionError(
        ...<4 lines>...
        ) from exc
    sphinx.errors.ExtensionError: Handler <function _run_doxygen at 0x73c134117ba0> for event 'config-inited' threw an exception (exception: Failed when running doxygen)
```

## Test Plan

N/A

## Test Result

N/A

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.