[hipblaslt][tensilelite] Exclude F6 from data initialization using mxDataGenerator (#7644)
## Motivation

https://github.com/ROCm/rocm-libraries/pull/7136 enabled data
initialization to use mxDataGenerator for F8 (previously only F4), and
introduced an assertion to disallow F6. However, this caused test
failures in 1250.
This PR excludes F6 for now, falling back to the original path (not
using mxDataGenerator) instead of throwing a runtime error.

## Technical Details

Exclude Float6 and BFloat6 from data generation using mxDataGenerator.

## Test Plan

I ran 1250 tests locally and two tests failed:
```
FAILED Tensile/Tests/common/test_config.py::test_config[Tensile/Tests/common/sparse/gfx1250/spmm_tdm_f16_transposes.yaml] - SystemExit: 1
FAILED Tensile/Tests/common/test_config.py::test_config[Tensile/Tests/common/gemm/nan_bounds_check_odd_padding.yaml] - AssertionError: Unhandled WMMA: (16, 16, 16, 1)
```
But these two tests fail even without this change, so they are likely
not related to this PR.
 

---

Many thanks to @jaopaulolc and @ThanHenderson for helping me set up the
1250 environment and reproduce the error!